// ==UserScript==
// @name         4chan XT
// @version      2.26.1
// @minGMVer     1.14
// @minFFVer     115
// @namespace    4chan-XT
// @description  4chan XT is a script that adds various features to anonymous imageboards.
// @license      MIT; https://github.com/burningwiththefiresoforc/4chan-xt/blob/project-XT/LICENSE
// @include      https://boards.4chan.org/*
// @include      https://sys.4chan.org/*
// @include      https://www.4chan.org/*
// @include      https://i.4cdn.org/*
// @include      https://is.4chan.org/*
// @include      https://is2.4chan.org/*
// @include      https://erischan.org/*
// @include      https://www.erischan.org/*
// @include      https://kakashinenpo.com/*
// @include      https://www.kakashinenpo.com/*
// @include      https://kissu.moe/*
// @include      https://www.kissu.moe/*
// @include      https://original.kissu.moe/*
// @include      https://lainchan.org/*
// @include      https://www.lainchan.org/*
// @include      https://merorin.com/*
// @include      https://ota-ch.com/*
// @include      https://www.ota-ch.com/*
// @include      https://sportschan.org/*
// @include      https://www.sportschan.org/*
// @include      https://sushigirl.us/*
// @include      https://www.sushigirl.us/*
// @exclude      https://www.4chan.org/advertise
// @exclude      https://www.4chan.org/advertise?*
// @exclude      https://www.4chan.org/donate
// @exclude      https://www.4chan.org/donate?*
// @exclude      https://www.4chan.org/
// @connect      4chan.org
// @connect      4cdn.org
// @connect      4chenz.github.io
// @connect      archive.4plebs.org
// @connect      warosu.org
// @connect      desuarchive.org
// @connect      boards.fireden.net
// @connect      arch.b4k.dev
// @connect      archived.moe
// @connect      api.clyp.it
// @connect      api.dailymotion.com
// @connect      api.github.com
// @connect      soundcloud.com
// @connect      api.streamable.com
// @connect      vimeo.com
// @connect      www.youtube.com
// @connect      *
// @grant        GM_getValue
// @grant        GM_setValue
// @grant        GM_deleteValue
// @grant        GM_listValues
// @grant        GM_addValueChangeListener
// @grant        GM_openInTab
// @grant        GM_xmlhttpRequest
// @grant        GM.getValue
// @grant        GM.setValue
// @grant        GM.deleteValue
// @grant        GM.listValues
// @grant        GM.openInTab
// @grant        GM.xmlHttpRequest
// @run-at       document-start
// @updateURL    https://github.com/burningwiththefiresoforc/4chan-xt/raw/refs/heads/project-XT/builds/4chan-XT.min.meta.js
// @downloadURL  https://github.com/burningwiththefiresoforc/4chan-xt/raw/refs/heads/project-XT/builds/4chan-XT.min.user.js
// @homepageURL  https://github.com/burningwiththefiresoforc/4chan-xt/
// @icon         data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAMAAABg3Am1AAAACVBMVEUAAGcAAABmzDNZt9VtAAAAAXRSTlMAQObYZgAAAF1JREFUeNrtkYEGwDAUxLb9/0cPNJB6BqLYobhc4PX6nj/3yoAagepZAWxRIMzAZSEIgLdlIBAv7DMOBLJ1mPaCHda9cOyV5p/uBV/TTS+YuewFXpexAOYdykA4Ly/hJQbBjgt3/wAAAABJRU5ErkJggg==
// @license      MIT
// ==/UserScript==
